"use client";
import {useState} from "react";
type Shift={id:string;worker:string;job:string;field:string;start:string;end:string};
type Time={id:string;worker:string;clockIn:string;clockOut?:string;gpsIn?:string;gpsOut?:string;approved?:boolean};
export default function TeamPage(){
 const [shifts,setShifts]=useState<Shift[]>([]),[times,setTimes]=useState<Time[]>([]),[active,setActive]=useState<string|null>(null),[message,setMessage]=useState("");
 const [shift,setShift]=useState({worker:"Worker 1",job:"Field work",field:"North Field",start:"",end:""});
 const joinCode="4CEC570164";
 function add(){if(!shift.start||!shift.end)return setMessage("Enter start and end times.");setShifts([{id:crypto.randomUUID(),...shift},...shifts]);setMessage("Shift scheduled locally.");}
 function gps(cb:(v:string)=>void){if(!navigator.geolocation)return cb("unavailable");navigator.geolocation.getCurrentPosition(p=>cb(`${p.coords.latitude.toFixed(6)},${p.coords.longitude.toFixed(6)} ±${Math.round(p.coords.accuracy)}m`),()=>cb("unavailable"),{enableHighAccuracy:true,timeout:15000});}
 function clockIn(){gps(g=>{const id=crypto.randomUUID();setTimes([{id,worker:"Worker 1",clockIn:new Date().toISOString(),gpsIn:g},...times]);setActive(id);setMessage("Clocked in.");});}
 function clockOut(){if(!active)return;gps(g=>{setTimes(ts=>ts.map(t=>t.id===active?{...t,clockOut:new Date().toISOString(),gpsOut:g}:t));setActive(null);setMessage("Clocked out.");});}
 function approve(id:string,v:boolean){setTimes(ts=>ts.map(t=>t.id===id?{...t,approved:v}:t));}
 function csv(){const rows=times.filter(t=>t.approved&&t.clockOut),esc=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const text=[["worker","clock_in_utc","clock_out_utc","gps_in","gps_out"].join(","),...rows.map(t=>[t.worker,t.clockIn,t.clockOut,t.gpsIn,t.gpsOut].map(esc).join(","))].join("\n");const b=new Blob([text],{type:"text/csv"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="approved-time.csv";a.click();URL.revokeObjectURL(u);}
 return <main className="container section stack"><div><div className="kicker">Team, schedule & time</div><h2>One farm team</h2><p className="muted">GPS is captured at clock events only; there is no continuous employee tracking.</p></div><div className="grid-2"><section className="card stack"><h3>Worker join code</h3><div className="stat">{joinCode}</div><p className="muted">Use the complete code. Employee IDs and farm join codes are different.</p><button className="btn secondary" onClick={()=>navigator.clipboard?.writeText(joinCode)}>Copy code</button></section><section className="card stack"><h3>Employee time clock</h3><div className="inline"><button className="btn" disabled={Boolean(active)} onClick={clockIn}>Clock in with GPS</button><button className="btn secondary" disabled={!active} onClick={clockOut}>Clock out with GPS</button></div></section></div>
 <section className="card form"><h3>Weekly scheduling</h3><div className="row"><div className="field"><label>Worker</label><input value={shift.worker} onChange={e=>setShift({...shift,worker:e.target.value})}/></div><div className="field"><label>Job</label><input value={shift.job} onChange={e=>setShift({...shift,job:e.target.value})}/></div></div><div className="field"><label>Field</label><input value={shift.field} onChange={e=>setShift({...shift,field:e.target.value})}/></div><div className="row"><div className="field"><label>Start</label><input type="datetime-local" value={shift.start} onChange={e=>setShift({...shift,start:e.target.value})}/></div><div className="field"><label>End</label><input type="datetime-local" value={shift.end} onChange={e=>setShift({...shift,end:e.target.value})}/></div></div><button className="btn" onClick={add}>Schedule shift</button>{shifts.length>0&&<table className="table"><tbody>{shifts.map(s=><tr key={s.id}><td>{s.worker}</td><td>{s.job} · {s.field}</td><td>{s.start}</td><td>{s.end}</td></tr>)}</tbody></table>}</section>
 <section className="card"><div className="inline" style={{justifyContent:"space-between"}}><h3>Manager review</h3><button className="btn secondary" onClick={csv}>Download approved-time CSV</button></div>{times.length?<table className="table"><thead><tr><th>Worker</th><th>Clock in</th><th>Clock out</th><th>GPS</th><th>Review</th></tr></thead><tbody>{times.map(t=><tr key={t.id}><td>{t.worker}</td><td>{new Date(t.clockIn).toLocaleString()}</td><td>{t.clockOut?new Date(t.clockOut).toLocaleString():"Active"}</td><td>{t.gpsIn}</td><td>{t.clockOut?<span className="inline"><button className="btn secondary" onClick={()=>approve(t.id,true)}>Approve</button><button className="btn secondary" onClick={()=>approve(t.id,false)}>Reject</button></span>:"—"}</td></tr>)}</tbody></table>:<p className="muted">No time entries yet.</p>}</section>{message&&<div className="notice">{message}</div>}</main>;
}