// Nationwide restricted-use pesticide (RUP) recordkeeping validation
// Federal baseline: 7 U.S.C. § 136i-1 and USDA AMS pesticide recordkeeping guidance.
//
// IMPORTANT:
// - Validates the federal private-applicator RUP baseline.
// - States may require additional fields, longer retention, or additional categories.
// - Run validatePesticideRecord() at the persistence boundary and block confirmed
//   saves when complete === false.
// - Add verified state-specific validators through STATE_VALIDATORS.

export interface PesticideRecord {
  applicatorName?: string;
  certificationNumber?: string;
  productName?: string;
  epaRegNumber?: string;
  amountApplied?: number | string;
  amountUnit?: string;
  cropOrSite?: string;
  fieldLocation?: string;
  areaTreated?: number | string;
  areaUnit?: string;
  applicationDate?: string; // YYYY-MM-DD
  recordCreatedAt?: string; // ISO timestamp, generated by the app
  state?: string;
  isRestrictedUse: boolean;
  isSpotTreatment?: boolean;
  isGreenhouseOrNursery?: boolean;
  stateFields?: Record<string, unknown>;
}

export interface ValidationIssue {
  field: string;
  label: string;
  source: "federal" | "state";
  kind: "missing" | "invalid" | "timing";
  message: string;
}

export interface ValidationResult {
  complete: boolean;
  missingFields: string[];
  invalidFields: string[];
  requiredFields: string[];
  issues: ValidationIssue[];
  federalComplete: boolean;
  stateComplete: boolean;
  federalSpotTreatmentUsed: boolean;
  recordEntryOverdue: boolean;
}

type FieldRequirement = {
  key: keyof PesticideRecord;
  label: string;
};

export type StateValidator = (record: PesticideRecord) => ValidationIssue[];

const FEDERAL_FULL_APPLICATION_FIELDS: FieldRequirement[] = [
  { key: "applicatorName", label: "Applicator name" },
  { key: "certificationNumber", label: "Certification number" },
  { key: "productName", label: "Brand or product name" },
  { key: "epaRegNumber", label: "EPA registration number" },
  { key: "amountApplied", label: "Total amount applied" },
  { key: "amountUnit", label: "Amount unit" },
  { key: "cropOrSite", label: "Crop, commodity, stored product, or site treated" },
  { key: "fieldLocation", label: "Application location" },
  { key: "areaTreated", label: "Size of area treated" },
  { key: "areaUnit", label: "Area unit" },
  { key: "applicationDate", label: "Date of application" },
];

const FEDERAL_SPOT_TREATMENT_FIELDS: FieldRequirement[] = [
  { key: "productName", label: "Brand or product name" },
  { key: "epaRegNumber", label: "EPA registration number" },
  { key: "amountApplied", label: "Total amount applied" },
  { key: "amountUnit", label: "Amount unit" },
  { key: "fieldLocation", label: "Spot application location" },
  { key: "applicationDate", label: "Date of application" },
];

function hasValue(value: unknown): boolean {
  if (value === undefined || value === null) return false;
  if (typeof value === "string") return value.trim().length > 0;
  if (typeof value === "number") return Number.isFinite(value);
  return true;
}

function positiveNumber(value: number | string | undefined): number | null {
  if (value === undefined || value === null) return null;
  const parsed = typeof value === "number" ? value : Number(value.trim());
  return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
}

function normalizeUnit(unit?: string): string {
  return unit?.trim().toLowerCase() ?? "";
}

function areaInAcres(record: PesticideRecord): number | null {
  const value = positiveNumber(record.areaTreated);
  if (value === null) return null;

  switch (normalizeUnit(record.areaUnit)) {
    case "acre":
    case "acres":
    case "ac":
      return value;
    case "sq ft":
    case "sqft":
    case "square foot":
    case "square feet":
    case "ft2":
    case "ft^2":
      return value / 43560;
    case "sq yd":
    case "sqyd":
    case "square yard":
    case "square yards":
    case "yd2":
    case "yd^2":
      return value / 4840;
    case "hectare":
    case "hectares":
    case "ha":
      return value * 2.4710538147;
    default:
      return null;
  }
}

function isValidIsoDate(value?: string): boolean {
  if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
  const date = new Date(`${value}T00:00:00Z`);
  if (Number.isNaN(date.getTime())) return false;
  return date.toISOString().slice(0, 10) === value;
}

function isPlausibleEpaRegNumber(value?: string): boolean {
  if (!value) return false;
  return /^\d+-\d+(?:-\d+)?$/.test(value.trim());
}

function validSpotLocation(value?: string): boolean {
  if (!value) return false;
  return /^spot (application|treatment)\b\s*[-:–—]?\s*\S+/i.test(value.trim());
}

function isRecordEntryOverdue(record: PesticideRecord): boolean {
  if (!record.applicationDate || !isValidIsoDate(record.applicationDate)) return false;

  const application = new Date(`${record.applicationDate}T00:00:00Z`);
  const created = record.recordCreatedAt ? new Date(record.recordCreatedAt) : new Date();

  if (Number.isNaN(created.getTime())) return false;

  const elapsedMs = created.getTime() - application.getTime();
  return elapsedMs > 14 * 24 * 60 * 60 * 1000;
}

export function qualifiesForFederalSpotTreatment(record: PesticideRecord): boolean {
  if (!record.isRestrictedUse || !record.isSpotTreatment || record.isGreenhouseOrNursery) {
    return false;
  }

  const acres = areaInAcres(record);
  return acres !== null && acres < 0.1;
}

function validateFederal(record: PesticideRecord): {
  issues: ValidationIssue[];
  requiredFields: string[];
  spotTreatmentUsed: boolean;
  recordEntryOverdue: boolean;
} {
  if (!record.isRestrictedUse) {
    return {
      issues: [],
      requiredFields: [],
      spotTreatmentUsed: false,
      recordEntryOverdue: false,
    };
  }

  const spotTreatmentUsed = qualifiesForFederalSpotTreatment(record);
  const fieldSet = spotTreatmentUsed
    ? FEDERAL_SPOT_TREATMENT_FIELDS
    : FEDERAL_FULL_APPLICATION_FIELDS;

  const issues: ValidationIssue[] = fieldSet
    .filter((field) => !hasValue(record[field.key]))
    .map((field) => ({
      field: String(field.key),
      label: field.label,
      source: "federal" as const,
      kind: "missing" as const,
      message: `${field.label} is required for this restricted-use pesticide record.`,
    }));

  if (hasValue(record.amountApplied) && positiveNumber(record.amountApplied) === null) {
    issues.push({
      field: "amountApplied",
      label: "Total amount applied",
      source: "federal",
      kind: "invalid",
      message: "Total amount applied must be a number greater than zero.",
    });
  }

  if (!spotTreatmentUsed && hasValue(record.areaTreated) && positiveNumber(record.areaTreated) === null) {
    issues.push({
      field: "areaTreated",
      label: "Size of area treated",
      source: "federal",
      kind: "invalid",
      message: "Size of area treated must be a number greater than zero.",
    });
  }

  if (hasValue(record.applicationDate) && !isValidIsoDate(record.applicationDate)) {
    issues.push({
      field: "applicationDate",
      label: "Date of application",
      source: "federal",
      kind: "invalid",
      message: "Application date must be a valid calendar date in YYYY-MM-DD format.",
    });
  }

  if (hasValue(record.epaRegNumber) && !isPlausibleEpaRegNumber(record.epaRegNumber)) {
    issues.push({
      field: "epaRegNumber",
      label: "EPA registration number",
      source: "federal",
      kind: "invalid",
      message: "EPA registration number should use a numeric hyphenated format such as 123-456 or 123-456-789.",
    });
  }

  if (spotTreatmentUsed && !validSpotLocation(record.fieldLocation)) {
    issues.push({
      field: "fieldLocation",
      label: "Spot application location",
      source: "federal",
      kind: "invalid",
      message:
        'For a federal spot-treatment record, begin the location with "Spot application" or "Spot treatment" and add a brief location description.',
    });
  }

  if (record.isSpotTreatment && !spotTreatmentUsed) {
    issues.push({
      field: "isSpotTreatment",
      label: "Spot treatment qualification",
      source: "federal",
      kind: "invalid",
      message:
        "This application does not qualify for the federal spot-treatment shortcut. Complete the full RUP record.",
    });
  }

  const recordEntryOverdue = isRecordEntryOverdue(record);

  if (recordEntryOverdue) {
    issues.push({
      field: "recordCreatedAt",
      label: "Record entry timing",
      source: "federal",
      kind: "timing",
      message:
        "This RUP record was entered more than 14 days after the application date. Keep the record, but flag it for compliance review.",
    });
  }

  return {
    issues,
    requiredFields: fieldSet.map((field) => field.label),
    spotTreatmentUsed,
    recordEntryOverdue,
  };
}

export const STATE_VALIDATORS: Partial<Record<string, StateValidator>> = {};

export function registerStateValidator(state: string, validator: StateValidator): void {
  STATE_VALIDATORS[state.trim().toUpperCase()] = validator;
}

function validateState(record: PesticideRecord): ValidationIssue[] {
  const state = record.state?.trim().toUpperCase();
  if (!state) return [];
  const validator = STATE_VALIDATORS[state];
  return validator ? validator(record) : [];
}

export function validatePesticideRecord(record: PesticideRecord): ValidationResult {
  const federal = validateFederal(record);
  const stateIssues = validateState(record);
  const allIssues = [...federal.issues, ...stateIssues];

  const blockingIssues = allIssues.filter((issue) => issue.kind !== "timing");
  const missingFields = allIssues
    .filter((issue) => issue.kind === "missing")
    .map((issue) => issue.label);
  const invalidFields = allIssues
    .filter((issue) => issue.kind === "invalid")
    .map((issue) => issue.message);

  const federalBlockingIssues = federal.issues.filter((issue) => issue.kind !== "timing");

  return {
    complete: blockingIssues.length === 0,
    missingFields,
    invalidFields,
    requiredFields: federal.requiredFields,
    issues: allIssues,
    federalComplete: federalBlockingIssues.length === 0,
    stateComplete: stateIssues.filter((issue) => issue.kind !== "timing").length === 0,
    federalSpotTreatmentUsed: federal.spotTreatmentUsed,
    recordEntryOverdue: federal.recordEntryOverdue,
  };
}

export function assertPesticideRecordComplete(record: PesticideRecord): void {
  const result = validatePesticideRecord(record);
  if (!result.complete) throw new PesticideRecordIncompleteError(result);
}

export class PesticideRecordIncompleteError extends Error {
  readonly result: ValidationResult;
  readonly missingFields: string[];
  readonly invalidFields: string[];

  constructor(result: ValidationResult) {
    const problems = [...result.missingFields, ...result.invalidFields];

    super(
      `Pesticide record is incomplete or invalid: ${problems.join(", ")}`
    );

    this.name = "PesticideRecordIncompleteError";
    this.result = result;
    this.missingFields = result.missingFields;
    this.invalidFields = result.invalidFields;
  }
}
