"use client";
import { useEffect,useMemo,useState } from "react";
import { validatePesticideRecord,type PesticideRecord } from "@/src/compliance/pesticide-record-validation";
import { csvFromRecords,loadRecords,saveRecord,type SavedRecord } from "@/src/lib/storage";
import { createClient } from "@/src/lib/supabase/client";
import { getFarmContext,loadCloudFields,type CloudField,type FarmContext } from "@/src/lib/farm-cloud";
const states=["AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"];
function download(name:string,text:string){const b=new Blob([text],{type:"text/csv"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
export default function RecordsPage(){
 const [supabase]=useState(()=>createClient());
 const [ctx,setCtx]=useState<FarmContext|null>(null),[fields,setFields]=useState<CloudField[]>([]),[fieldId,setFieldId]=useState("");
 const [recent,setRecent]=useState<SavedRecord[]>([]),[message,setMessage]=useState(""),[transcript,setTranscript]=useState("");
 const [gps,setGps]=useState<{lat:number;lng:number;accuracy:number;capturedAt:string}|null>(null);
 const [record,setRecord]=useState<PesticideRecord>({isRestrictedUse:true,state:"NC",areaUnit:"acres",amountUnit:"gallons"});
 useEffect(()=>{setRecent(loadRecords());void(async()=>{try{const c=await getFarmContext(supabase);setCtx(c);if(!c)return;const f=await loadCloudFields(supabase,c.farmId);setFields(f);}catch(e){setMessage(`Cloud records unavailable; offline drafts remain available: ${e instanceof Error?e.message:"Unknown error"}`);}})();},[supabase]); const validation=useMemo(()=>validatePesticideRecord(record),[record]);
 const set=(k:keyof PesticideRecord,v:unknown)=>setRecord(r=>({...r,[k]:v}));
 function captureGps(){if(!navigator.geolocation)return setMessage("Geolocation is unavailable.");navigator.geolocation.getCurrentPosition(p=>setGps({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,capturedAt:new Date().toISOString()}),e=>setMessage(`GPS unavailable: ${e.message}`),{enableHighAccuracy:true,timeout:15000,maximumAge:0});}
 function voice(){const w=window as Window&{webkitSpeechRecognition?:new()=>any};if(!w.webkitSpeechRecognition)return setMessage("Voice recognition is unavailable in this browser. Type the note instead.");const s=new w.webkitSpeechRecognition();s.lang="en-US";s.onresult=(e:any)=>setTranscript(t=>`${t}${t?" ":""}${e.results[0][0].transcript}`);s.onerror=(e:any)=>setMessage(`Voice recognition error: ${e.error}`);s.start();}
 async function save(status:"draft"|"confirmed"){const createdAt=new Date().toISOString();const selectedField=fields.find(f=>f.id===fieldId);const recordForSave={...record,recordCreatedAt:createdAt,fieldLocation:record.fieldLocation||selectedField?.name};const v=validatePesticideRecord(recordForSave);if(status==="confirmed"&&record.isRestrictedUse&&!v.complete){const problems=[...v.missingFields,...v.invalidFields];return setMessage(`Cannot confirm this RUP record. ${problems.join("; ")}`);}const payload={...recordForSave,transcript,gps};if(ctx){const {data,error}=await supabase.from("farm_records").insert({farm_id:ctx.farmId,created_by:ctx.userId,field_id:fieldId||null,record_type:"pesticide",status,payload,recording_lat:gps?.lat??null,recording_lng:gps?.lng??null,recording_accuracy_m:gps?.accuracy??null,recording_captured_at:gps?.capturedAt??null}).select("id,created_at,status").single();if(!error&&data){setRecord(recordForSave);setMessage(`${status==="draft"?"Draft":"Confirmed record"} saved to FarmVoice cloud.${v.recordEntryOverdue?" Warning: entered more than 14 days after the application date.":""}`);return;}setMessage(`Cloud save unavailable${error?`: ${error.message}`:""}. Saving an offline copy on this device.`);}saveRecord({id:crypto.randomUUID(),type:"pesticide",createdAt,status,payload});setRecent(loadRecords());setRecord(recordForSave);setMessage(`${status==="draft"?"Draft":"Confirmed record"} saved offline on this device.${v.recordEntryOverdue?" Warning: entered more than 14 days after the application date.":""}`);}
 return <main className="container section stack"><div><div className="kicker">Field records</div><h2>Speak, review and save</h2><p className="muted">GPS can be captured when recording. Confirmed RUP records are blocked until the federal baseline fields are complete.</p></div><div className="grid-2"><section className="card form"><div className="inline"><button className="btn secondary" onClick={voice}>Start recording</button><button className="btn secondary" onClick={captureGps}>Capture GPS</button></div><div className="field"><label>Original spoken/typed note</label><textarea value={transcript} onChange={e=>setTranscript(e.target.value)}/></div>{gps&&<div className="notice">GPS {gps.lat.toFixed(6)}, {gps.lng.toFixed(6)} · ±{Math.round(gps.accuracy)}m <button className="btn secondary" onClick={()=>setGps(null)}>Remove</button></div>}
 <div className="field"><label>Farm field / production area</label><select value={fieldId} onChange={e=>{setFieldId(e.target.value);const f=fields.find(x=>x.id===e.target.value);if(f)set("fieldLocation",f.name);}}><option value="">Select field (optional)</option>{fields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="row"><div className="field"><label>State</label><select value={record.state} onChange={e=>set("state",e.target.value)}>{states.map(s=><option key={s}>{s}</option>)}</select></div><div className="field"><label>Application date</label><input type="date" value={String(record.applicationDate??"")} onChange={e=>set("applicationDate",e.target.value)}/></div></div>
 <div className="row"><div className="field"><label>Applicator name</label><input value={String(record.applicatorName??"")} onChange={e=>set("applicatorName",e.target.value)}/></div><div className="field"><label>Certification number</label><input value={String(record.certificationNumber??"")} onChange={e=>set("certificationNumber",e.target.value)}/></div></div>
 <div className="row"><div className="field"><label>Product name</label><input value={String(record.productName??"")} onChange={e=>set("productName",e.target.value)}/></div><div className="field"><label>EPA registration number</label><input value={String(record.epaRegNumber??"")} onChange={e=>set("epaRegNumber",e.target.value)}/></div></div>
 <div className="row"><div className="field"><label>Total amount applied</label><input value={String(record.amountApplied??"")} onChange={e=>set("amountApplied",e.target.value)}/></div><div className="field"><label>Amount unit</label><input value={String(record.amountUnit??"")} onChange={e=>set("amountUnit",e.target.value)}/></div></div>
 <div className="field"><label>Crop, commodity, or site treated</label><input value={String(record.cropOrSite??"")} onChange={e=>set("cropOrSite",e.target.value)}/></div><div className="field"><label>Field / location</label><input value={String(record.fieldLocation??"")} onChange={e=>set("fieldLocation",e.target.value)} placeholder={record.isSpotTreatment?"Spot application - north fence line":"North Field"}/></div>
 <div className="row"><div className="field"><label>Size of area treated</label><input value={String(record.areaTreated??"")} onChange={e=>set("areaTreated",e.target.value)}/></div><div className="field"><label>Area unit</label><select value={String(record.areaUnit??"acres")} onChange={e=>set("areaUnit",e.target.value)}><option>acres</option><option>sq ft</option><option>sq yd</option><option>hectares</option></select></div></div>
 <label className="inline"><input type="checkbox" checked={record.isRestrictedUse} onChange={e=>set("isRestrictedUse",e.target.checked)}/> Restricted-use pesticide</label><label className="inline"><input type="checkbox" checked={Boolean(record.isSpotTreatment)} onChange={e=>set("isSpotTreatment",e.target.checked)}/> Federal spot-treatment shortcut requested</label><label className="inline"><input type="checkbox" checked={Boolean(record.isGreenhouseOrNursery)} onChange={e=>set("isGreenhouseOrNursery",e.target.checked)}/> Greenhouse or nursery</label><div className="inline"><button className="btn secondary" onClick={()=>void save("draft")}>Save draft</button><button className="btn" onClick={()=>void save("confirmed")}>Confirm & save</button></div></section>
 <aside className="stack"><div className={`notice ${record.isRestrictedUse&&!validation.complete?"warn":""}`}><strong>{record.isRestrictedUse?(validation.complete?"Federal USDA RUP record fields complete":"Federal USDA RUP record needs review"):"Federal RUP validator not applicable"}</strong>{validation.federalSpotTreatmentUsed&&<p className="small"><strong>Federal spot-treatment shortcut:</strong> qualified from the entered area and application type.</p>}{record.isSpotTreatment&&!validation.federalSpotTreatmentUsed&&<p className="small"><strong>Spot-treatment shortcut:</strong> not qualified; full RUP fields apply.</p>}{validation.missingFields.length>0&&<><p className="small"><strong>Missing required fields</strong></p><ul className="list">{validation.missingFields.map(x=><li key={`missing-${x}`}>{x}</li>)}</ul></>}{validation.invalidFields.length>0&&<><p className="small"><strong>Invalid values</strong></p><ul className="list">{validation.invalidFields.map(x=><li key={`invalid-${x}`}>{x}</li>)}</ul></>}{validation.recordEntryOverdue&&<p className="notice warn small">Federal timing warning: this RUP record was entered more than 14 days after the application date. Keep the record and flag it for compliance review.</p>}<p className="small">Field completeness is not legal certification. State, WPS, applicator-license and product-label requirements may add obligations.</p></div></aside></div>
 {message&&<div className="notice">{message}</div>}<section className="card"><div className="inline" style={{justifyContent:"space-between"}}><h3>Recent records</h3><button className="btn secondary" disabled={!recent.length} onClick={()=>download("farmvoice-records.csv",csvFromRecords(recent))}>Download records</button></div>{recent.length?<table className="table"><thead><tr><th>Type</th><th>Status</th><th>Created</th></tr></thead><tbody>{recent.slice(0,8).map(r=><tr key={r.id}><td>{r.type}</td><td>{r.status}</td><td>{new Date(r.createdAt).toLocaleString()}</td></tr>)}</tbody></table>:<p className="muted">No local records yet.</p>}</section></main>;
}