"use client";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/src/lib/supabase/client";
import { getFarmContext,loadCloudFields,loadCloudFieldHistory,type CloudField,type CloudHistoryEvent,type FarmContext } from "@/src/lib/farm-cloud";

const empty={name:"",areaType:"field",sizeValue:"",sizeUnit:"acres",currentCrop:"",previousLandUse:"",plantingDate:"",harvestDate:"",organicStatus:"unknown",bufferNotes:"",adjoiningLandNotes:"",boundaryNotes:"",managementNotes:""};

export default function FieldsPage(){
 const [supabase]=useState(()=>createClient());
 const [ctx,setCtx]=useState<FarmContext|null>(null),[fields,setFields]=useState<CloudField[]>([]),[history,setHistory]=useState<CloudHistoryEvent[]>([]),[form,setForm]=useState(empty),[selected,setSelected]=useState(""),[eventType,setEventType]=useState("note"),[eventDate,setEventDate]=useState(""),[summary,setSummary]=useState(""),[message,setMessage]=useState("Loading cloud fields...");
 const set=(k:keyof typeof empty,v:string)=>setForm(f=>({...f,[k]:v}));
 async function refresh(farmId:string){const [f,h]=await Promise.all([loadCloudFields(supabase,farmId),loadCloudFieldHistory(supabase,farmId)]);setFields(f);setHistory(h);if(!selected&&f[0])setSelected(f[0].id);}
 useEffect(()=>{void(async()=>{try{const c=await getFarmContext(supabase);setCtx(c);if(!c){setMessage("Sign in and join or create a farm before using cloud field history.");return;}await refresh(c.farmId);setMessage("Cloud field history is connected.");}catch(e){setMessage(`Cloud fields unavailable: ${e instanceof Error?e.message:"Unknown error"}`);}})();},[supabase]);
 const active=fields.find(f=>f.id===selected)??fields[0];const events=useMemo(()=>active?history.filter(h=>h.field_id===active.id):[],[history,active]);
 async function addField(){if(!ctx)return setMessage("Sign in and join a farm first.");if(!form.name.trim())return setMessage("Enter a field or location name.");const {data,error}=await supabase.from("fields").insert({farm_id:ctx.farmId,name:form.name.trim(),area_type:form.areaType,size_value:form.sizeValue?Number(form.sizeValue):null,size_unit:form.sizeUnit,current_crop:form.currentCrop||null,previous_land_use:form.previousLandUse||null,planting_date:form.plantingDate||null,harvest_date:form.harvestDate||null,organic_status:form.organicStatus,buffer_notes:form.bufferNotes||null,adjoining_land_notes:form.adjoiningLandNotes||null,boundary_notes:form.boundaryNotes||null,management_notes:form.managementNotes||null,created_by:ctx.userId}).select("id").single();if(error)return setMessage(`Could not create field: ${error.message}`);setForm(empty);setSelected(data.id);await refresh(ctx.farmId);setMessage("Field profile saved to FarmVoice cloud.");}
 async function addEvent(){if(!ctx||!active)return setMessage("Create or select a field first.");if(!summary.trim())return setMessage("Enter a history summary.");const {error}=await supabase.from("field_history_events").insert({field_id:active.id,farm_id:ctx.farmId,event_type:eventType,event_date:eventDate||null,summary:summary.trim(),created_by:ctx.userId});if(error)return setMessage(`Could not save history: ${error.message}`);setSummary("");setEventDate("");await refresh(ctx.farmId);setMessage("Field history saved to FarmVoice cloud.");}
 return <main className="container section stack"><div><div className="kicker">Production areas</div><h2>Fields & history</h2><p className="muted">Persistent farm profiles and management history stored in Supabase and protected by farm membership.</p></div>
 <div className="grid-2"><section className="card form"><h3>Add field or production area</h3><div className="row"><div className="field"><label>Name</label><input value={form.name} onChange={e=>set("name",e.target.value)} placeholder="North Field"/></div><div className="field"><label>Type</label><select value={form.areaType} onChange={e=>set("areaType",e.target.value)}><option>field</option><option>bed</option><option>greenhouse</option><option>pasture</option><option>orchard</option><option>block</option><option>other</option></select></div></div>
 <div className="row"><div className="field"><label>Size</label><input inputMode="decimal" value={form.sizeValue} onChange={e=>set("sizeValue",e.target.value)}/></div><div className="field"><label>Unit</label><select value={form.sizeUnit} onChange={e=>set("sizeUnit",e.target.value)}><option>acres</option><option>sq ft</option><option>sq yd</option><option>hectares</option></select></div></div>
 <div className="row"><div className="field"><label>Current crop</label><input value={form.currentCrop} onChange={e=>set("currentCrop",e.target.value)}/></div><div className="field"><label>Organic status</label><select value={form.organicStatus} onChange={e=>set("organicStatus",e.target.value)}><option value="unknown">Unknown</option><option value="not_organic">Not organic</option><option value="transition">Transition</option><option value="certified_organic">Certified organic</option><option value="exempt">Exempt</option></select></div></div>
 <div className="row"><div className="field"><label>Planting date</label><input type="date" value={form.plantingDate} onChange={e=>set("plantingDate",e.target.value)}/></div><div className="field"><label>Harvest date</label><input type="date" value={form.harvestDate} onChange={e=>set("harvestDate",e.target.value)}/></div></div>
 <div className="field"><label>Previous land use / crops</label><textarea value={form.previousLandUse} onChange={e=>set("previousLandUse",e.target.value)}/></div><div className="field"><label>Buffer areas</label><textarea value={form.bufferNotes} onChange={e=>set("bufferNotes",e.target.value)}/></div><div className="field"><label>Adjoining land</label><textarea value={form.adjoiningLandNotes} onChange={e=>set("adjoiningLandNotes",e.target.value)}/></div><div className="field"><label>Boundary changes</label><textarea value={form.boundaryNotes} onChange={e=>set("boundaryNotes",e.target.value)}/></div><div className="field"><label>Management notes</label><textarea value={form.managementNotes} onChange={e=>set("managementNotes",e.target.value)}/></div><button className="btn" onClick={()=>void addField()} disabled={!ctx}>Create field</button></section>
 <aside className="stack"><section className="card"><h3>Fields</h3>{fields.length?<div className="stack">{fields.map(f=><button key={f.id} className="btn secondary" onClick={()=>setSelected(f.id)}>{f.name} · {f.size_value??"—"} {f.size_unit??""}</button>)}</div>:<p className="muted">No cloud fields yet.</p>}</section>
 {active&&<section className="card form"><h3>{active.name} history</h3><p className="small">{active.area_type} · {active.size_value??"—"} {active.size_unit??""}{active.current_crop?` · ${active.current_crop}`:""}</p><div className="row"><div className="field"><label>Event</label><select value={eventType} onChange={e=>setEventType(e.target.value)}><option value="crop">Crop</option><option value="planting">Planting</option><option value="harvest">Harvest</option><option value="input">Input applied</option><option value="land_use">Land use</option><option value="organic_status">Organic status</option><option value="buffer">Buffer</option><option value="boundary">Boundary</option><option value="adjoining_land">Adjoining land</option><option value="management_change">Management change</option><option value="note">Note</option></select></div><div className="field"><label>Date</label><input type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)}/></div></div><div className="field"><label>Summary</label><textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Applied compost to north half..."/></div><button className="btn" onClick={()=>void addEvent()}>Add to history</button>{events.length?<ul className="list">{events.map(e=><li key={e.id}><strong>{e.event_date||new Date(e.created_at).toLocaleDateString()}</strong> · {e.event_type.replaceAll("_"," ")} — {e.summary}</li>)}</ul>:<p className="muted">No history events yet.</p>}</section>}</aside></div>{message&&<div className="notice">{message}</div>}</main>;
}