"use client";
import { useEffect,useMemo,useState } from "react";

type FieldProfile={id:string;name:string;areaType:string;sizeValue:string;sizeUnit:string;currentCrop:string;previousLandUse:string;plantingDate:string;harvestDate:string;organicStatus:string;bufferNotes:string;adjoiningLandNotes:string;boundaryNotes:string;managementNotes:string;createdAt:string};
type HistoryEvent={id:string;fieldId:string;eventType:string;eventDate:string;summary:string;createdAt:string};
const FIELDS_KEY="farmvoice-fields-v1",HISTORY_KEY="farmvoice-field-history-v1";
const empty={name:"",areaType:"field",sizeValue:"",sizeUnit:"acres",currentCrop:"",previousLandUse:"",plantingDate:"",harvestDate:"",organicStatus:"unknown",bufferNotes:"",adjoiningLandNotes:"",boundaryNotes:"",managementNotes:""};
function read<T>(key:string):T[]{try{return JSON.parse(localStorage.getItem(key)||"[]") as T[]}catch{return[]}}
function write<T>(key:string,rows:T[]){localStorage.setItem(key,JSON.stringify(rows))}
export default function FieldsPage(){
 const [fields,setFields]=useState<FieldProfile[]>([]),[history,setHistory]=useState<HistoryEvent[]>([]),[form,setForm]=useState(empty),[selected,setSelected]=useState(""),[eventType,setEventType]=useState("note"),[eventDate,setEventDate]=useState(""),[summary,setSummary]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{setFields(read<FieldProfile>(FIELDS_KEY));setHistory(read<HistoryEvent>(HISTORY_KEY));},[]);
 const active=fields.find(f=>f.id===selected)??fields[0]; const events=useMemo(()=>active?history.filter(h=>h.fieldId===active.id).sort((a,b)=>(b.eventDate||b.createdAt).localeCompare(a.eventDate||a.createdAt)):[],[history,active]);
 const set=(k:keyof typeof empty,v:string)=>setForm(f=>({...f,[k]:v}));
 function addField(){if(!form.name.trim())return setMessage("Enter a field or location name.");const row:FieldProfile={id:crypto.randomUUID(),...form,name:form.name.trim(),createdAt:new Date().toISOString()};const next=[row,...fields];write(FIELDS_KEY,next);setFields(next);setSelected(row.id);setForm(empty);setMessage("Field profile created. Cloud sync uses the new Supabase fields schema when connected.");}
 function addEvent(){if(!active)return setMessage("Create a field first.");if(!summary.trim())return setMessage("Enter a history summary.");const row:HistoryEvent={id:crypto.randomUUID(),fieldId:active.id,eventType,eventDate,summary:summary.trim(),createdAt:new Date().toISOString()};const next=[row,...history];write(HISTORY_KEY,next);setHistory(next);setSummary("");setEventDate("");setMessage("History event added.");}
 return <main className="container section stack"><div><div className="kicker">Production areas</div><h2>Fields & history</h2><p className="muted">Keep a persistent profile for each field, bed, greenhouse, pasture, orchard or production block, then build its management history over time.</p></div>
 <div className="grid-2"><section className="card form"><h3>Add field or production area</h3><div className="row"><div className="field"><label>Name</label><input value={form.name} onChange={e=>set("name",e.target.value)} placeholder="North Field"/></div><div className="field"><label>Type</label><select value={form.areaType} onChange={e=>set("areaType",e.target.value)}><option>field</option><option>bed</option><option>greenhouse</option><option>pasture</option><option>orchard</option><option>block</option><option>other</option></select></div></div>
 <div className="row"><div className="field"><label>Size</label><input value={form.sizeValue} onChange={e=>set("sizeValue",e.target.value)}/></div><div className="field"><label>Unit</label><select value={form.sizeUnit} onChange={e=>set("sizeUnit",e.target.value)}><option>acres</option><option>sq ft</option><option>sq yd</option><option>hectares</option></select></div></div>
 <div className="row"><div className="field"><label>Current crop</label><input value={form.currentCrop} onChange={e=>set("currentCrop",e.target.value)}/></div><div className="field"><label>Organic status</label><select value={form.organicStatus} onChange={e=>set("organicStatus",e.target.value)}><option value="unknown">Unknown</option><option value="not_organic">Not organic</option><option value="transition">Transition</option><option value="certified_organic">Certified organic</option><option value="exempt">Exempt</option></select></div></div>
 <div className="row"><div className="field"><label>Planting date</label><input type="date" value={form.plantingDate} onChange={e=>set("plantingDate",e.target.value)}/></div><div className="field"><label>Harvest date</label><input type="date" value={form.harvestDate} onChange={e=>set("harvestDate",e.target.value)}/></div></div>
 <div className="field"><label>Previous land use / crops</label><textarea value={form.previousLandUse} onChange={e=>set("previousLandUse",e.target.value)}/></div><div className="field"><label>Buffer areas</label><textarea value={form.bufferNotes} onChange={e=>set("bufferNotes",e.target.value)}/></div><div className="field"><label>Adjoining land</label><textarea value={form.adjoiningLandNotes} onChange={e=>set("adjoiningLandNotes",e.target.value)}/></div><div className="field"><label>Boundary changes</label><textarea value={form.boundaryNotes} onChange={e=>set("boundaryNotes",e.target.value)}/></div><div className="field"><label>Management notes</label><textarea value={form.managementNotes} onChange={e=>set("managementNotes",e.target.value)}/></div><button className="btn" onClick={addField}>Create field</button></section>
 <aside className="stack"><section className="card"><h3>Fields</h3>{fields.length?<div className="stack">{fields.map(f=><button key={f.id} className="btn secondary" onClick={()=>setSelected(f.id)}>{f.name} · {f.sizeValue||"—"} {f.sizeUnit}</button>)}</div>:<p className="muted">No fields created yet.</p>}</section>
 {active&&<section className="card form"><h3>{active.name} history</h3><p className="small">{active.areaType} · {active.sizeValue||"—"} {active.sizeUnit}{active.currentCrop?` · ${active.currentCrop}`:""}</p><div className="row"><div className="field"><label>Event</label><select value={eventType} onChange={e=>setEventType(e.target.value)}><option value="crop">Crop</option><option value="planting">Planting</option><option value="harvest">Harvest</option><option value="input">Input applied</option><option value="land_use">Land use</option><option value="organic_status">Organic status</option><option value="buffer">Buffer</option><option value="boundary">Boundary</option><option value="adjoining_land">Adjoining land</option><option value="management_change">Management change</option><option value="note">Note</option></select></div><div className="field"><label>Date</label><input type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)}/></div></div><div className="field"><label>Summary</label><textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Applied compost to north half..."/></div><button className="btn" onClick={addEvent}>Add to history</button>{events.length?<ul className="list">{events.map(e=><li key={e.id}><strong>{e.eventDate||new Date(e.createdAt).toLocaleDateString()}</strong> · {e.eventType.replaceAll("_"," ")} — {e.summary}</li>)}</ul>:<p className="muted">No history events yet.</p>}</section>}</aside></div>{message&&<div className="notice">{message}</div>}</main>;
}